### ISSUE TITLE
Setup FlareSolverr with Jackett

### ISSUE THREAD

**Issue by yleflour** [l3uddz/cloudplow#100]
**Describe the problem**
The most popular torrent sites are protected by DDOS protection. To get around this issue [Jacket has added support](https://github.com/Jackett/Jackett#configuring-flaresolverr) for [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr)

**Describe any solutions you think might work**
- Add a new role configuring FlareSolverr in the base provisioning or as an extra role
- Add a configuration step in the doc to configure Jackett with FlareSolverr

I would love to add it myself but I don't have a lot of free time on hand and I'm not versed well enough with ansible to create a PR for it efficiently

**Comment by Torkiliuz** [comment]
How is FlareSolverr relevant for Cloudplow?

**Comment by saltydk** [comment]
I am also struggling to see the relevance to Cloudplow.
