### ISSUE TITLE
Schedular for pause or speed limits

### ISSUE THREAD

**Issue by Vandiliz3r** [l3uddz/cloudplow#103]
Good Day, 

Can you please assist/point me in the correct direction.

Is it possible to pause or limit the sync speeds?

If not would it be possible to add as a feature as I would like to limit upload speeds during the day and pause when I am home.

Regards

**Comment by fuzxi** [comment]
Yes, this is possible by adding --bwlimit (with arguments) in the rclone extras section of the remotes you want to schedule. 

See https://rclone.org/docs/#bwlimit-bandwidth-spec for details.

**Comment by saltydk** [comment]
Rclone flags can handle most of this so closing the issue.
