### ISSUE TITLE
non-default config location upload , config not found

### ISSUE THREAD

**Issue by TMD20** [l3uddz/cloudplow#122]
Hello

I think their is a bug with getting non-default config files
```
rclone_data = subprocess.check_output('rclone config dump', shell=True)
```
This leads to issues if the config file is not in a default location
as their will be no remotes in rclone_data

As it will check for the config in /config/rclone/rclone.conf
as stated here
https://rclone.org/docs/#config-config-file

A temporary fix would be to add the rclone_config enviromental variable.

But a more permanent one would be to change the line to
```
rclone_data = 
subprocess.check_output('rclone config --config={cmd_quote(self.rclone_config_path)} dump', shell=True)

```

**Comment by saltydk** [comment]
Should be fixed now, sorry for the slow response.
