### ISSUE TITLE
Use with Cache Mounted Remotes?

### ISSUE THREAD

**Issue by bassrock** [l3uddz/cloudplow#13]
Is it possible to use this script with an rclone cache remote that is already mounted? I have had issues with multiple rclone uses against the same cache remote at the same time.

**Comment by bassrock** [comment]
Also I am working on an unRAID plugin that uses your awesome scripts, hence the question: https://github.com/bassrock/unRAID-plugins

**Comment by desimaniac** [comment]
I believe if you set Cloudplow to upload to the "source" rclone remote (not the rclone cache one), it will be OK.

**Comment by bassrock** [comment]
So I have tried that. The issue is then the cache is actually invalidated and needs to be updated. 

Say for instance I have a file called test on my remote, I then delete it in the unionfs mount. Once I run the cleaner it will remove it from the remote, but not from my rclone cache so the file test will then reappear on my unionfs mount.

**Comment by bassrock** [comment]
Hmm i think if we start the rlcone mount with the --rc we might be able to then use that command to invalidate portions of the cache.

**Comment by bassrock** [comment]
So actually I ended up doing this with the local mount and the new offline uploading.

**Comment by LooseSeal2** [comment]
@bassrock please update your docker image or share the docker file you made please.
