### ISSUE TITLE
Ability to run commands after cloudplow upload process finishes

### ISSUE THREAD

**Issue by shaboigan** [l3uddz/cloudplow#29]
Currently I use a cron to run a script to upload to the cloud and once it finishes it runs a curl to resume sabnzbd as the disk space will be free again and sabnzbd doesn't have a resume function.

Is there any way to add extra commands to the end of the cloudplow upload process?

**Comment by tobifanibi** [comment]
I've added a pull request for this 
https://github.com/l3uddz/cloudplow/pull/94
