### ISSUE TITLE
Clean Multiple Remotes

### ISSUE THREAD

**Issue by sbcrumb** [l3uddz/cloudplow#38]
Is there anyway to have cloudplow clean multiple remotes? IE fails on remote 1 tries remote 2?
Reason is I started my collection encrypted. (Will take me too long to move to unencrypted.)
So I started anything new in a unencrypted. But sometimes Radarr/Sonarr downloads an upgrade for something on the old encrypted mount which is really just a read only space. And cloudplow will try to clean it but it can't cause it is on the old encrypted mount not the new non encrypted. Hopefully that made sense.

**Comment by desimaniac** [comment]
It will clean from whatever remote you have mentioned in the config section. 

```
    "hidden": {
        "/mnt/local/.unionfs-fuse": {
            "hidden_remotes": [
                "google"
            ]
        }
```

PS. You are in Discord aren't you? Why not ask there? Issues are more for actual issues (eg bugs), not for support.

**Comment by desimaniac** [comment]
```
    "hidden": {
        "/mnt/local/.unionfs-fuse": {
            "hidden_remotes": [
                "remote1",
                "remote2",
            ]
        }
```

These remotes are referring to CP config remotes not rclone remotes. So you need to create another remote under remotes section of the CP config.

**Comment by sbcrumb** [comment]
I think I got it sorry for opening an issue versus discord. Thanks for the direction.

**Comment by desimaniac** [comment]
Np. You can also PM me there.
