### ISSUE TITLE
Remote Duplicate Directory

### ISSUE THREAD

**Issue by theweasley** [l3uddz/cloudplow#57]
**Background:** I'm running Cloudplow with Cloudbox on a remote server to manage my plex library. I have a Gdrive linked to this remote server where Cloudplow uploads all the media. 

**Problem:** My Gdrive Media/Movies folder already had movies in it prior to me connecting it to the remote server. I also downloaded higher-res versions (4K) of the same movies on my remote server. I want to keep both versions for multiple playback options on plex (1080p and 4K). The names of the movie folders are the same on both the remote server and the Gdrive. So now when Cloudplow tries to upload to Gdrive, it gives a Duplicate Directory error and ignores the upload for these movies with multiple versions. 

**Question:** How can I disable this feature in Cloudplow such that the duplicate folders are not ignored and Cloudplow uploads and merges the files into the same duplicate folder on Gdrive?

**Comment by desimaniac** [comment]
Run rclone dedupe.

**Comment by theweasley** [comment]
> Run rclone dedupe.

Thanks! I've googled the command and it seems like this is indeed what I need to do. However, the command looks fairly complicated and I'm very new to linux. Any chance you could help me type the right command with the right parameters for my case? Some light reading on the command also tells me that users have had trouble getting dedupe to work correctly; hitting rate limits, more duplicates created than before, etc.

**Comment by desimaniac** [comment]
`rclone dedupe yourremotename:`

**Comment by theweasley** [comment]
Perfect, thanks! 

So just to reconfirm; if I run
`rclone dedupe yourremotename:media/path`

it will first compare remote and source for duplicate folders and then upload the source files from the source duplicate directory into the remote duplicate directory?

**Comment by desimaniac** [comment]
Google Drive allows duplicate folders to be created on their "filesystem". Rclone has issues uploading to such folders where a duplicate exists in the same parent folder. The error you saw was an error from Rclone itself since Cloudplow is a wrapper for Rclone.

**Comment by theweasley** [comment]
Okay I think it worked perfectly. I ran the command with `--dry-run -v` first to see what would happen with the actual command. Everything seemed to go as you said it would so then I ran the final command as:

`rclone dedupe google:Media -v`

Cloudplow then finished its uploads and there's nothing left in my source folder anymore. The log says some duplicates were merged.

Cheers desimaniac.
