### ISSUE TITLE
mover and rclone 1.48

### ISSUE THREAD

**Issue by fragment1** [l3uddz/cloudplow#62]
I noticed rclone 1.48 changelog included:

> Drive
> - Fix move and copy from TeamDrive to GDrive (Fionera)
> - Add notes that cleanup works in the background on drive (Nick Craig-Wood)
> - Add **--drive-server-side-across-configs** to default back to old server side copy semantics by default (Nick Craig-Wood)
> - Add --drive-size-as-quota to show storage quota usage for file size (Garry McNulty)

Would this alleviate the need for using rclone 1.47-019 for the mover feature that migrates from TD to MD?

Thanks!

**Comment by fragment1** [comment]
Just tested it with rclone v1.48.0 with the following addition under uploader, in mover:

 "mover": {
                "enabled": true,
                "move_from_remote": "staging:/Media",
                "move_to_remote": "google:/Media",
                "rclone_extras": {
                    "--delete-empty-src-dirs": null,
                    "--create-empty-src-dirs": null,
                    **"--drive-server-side-across-configs": null,**
                    "--stats": "60s",
                    "--verbose": 1,
                    "--no-traverse": null,
                    "--user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
                }

**Comment by desimaniac** [comment]
Yup. Thanks.
