### ISSUE TITLE
Failed to send discord notifications

### ISSUE THREAD

**Issue by HeroXx** [l3uddz/cloudplow#75]
**Describe the bug**

**To Reproduce**
- Enable discord notifications via apprise in the config
- Wait for a scheduled upload to begin
- Look at the logs, notice that discord notification haven't completed and this is the error message:
end                           - Failed to send Discord notification: Bad Request - Unsupported Parameters., error=400.

**Expected behavior**
Discord notifications should be sent via apprise successfully

**Screenshots**

**Logs**
end                           - Failed to send Discord notification: Bad Request - Unsupported Parameters., error=400.

You can enable debug mode by adding `--loglevel=DEBUG` to the run command (e.g. systemd).

**System Information**

 - Cloudplow Version: Master (latest)
 - Operating System: Ubuntu 19.04

**Additional context**

**Comment by nemchik** [comment]
Fixed in https://github.com/l3uddz/cloudplow/pull/70
