### ISSUE TITLE
Add local check before throttling

### ISSUE THREAD

**Issue by bigbozza** [l3uddz/cloudplow#76]
I host locally and it was bothering me that when I was watching locally, it was throttling my uploads unnecessarily.

I made changes to the main cloudplow.py and utils/plex.py so that it doesn't count them. I think it would be a good option for those of us who aren't 100% cloud.

In the PlexStream class from plex.py:
if 'Player' in stream:
            self.player = stream['Player']['product']
            self.ip = stream['Player']['remotePublicAddress']
            **self.local = stream['Player']['local']**

And at the bottom of plex.py:
        return u"{user} is playing {media} using {player}. " \
               "Stream state: {state}, type: {type}, **local: {local}.**".format(user=self.user,
                                                             media=self.title,
                                                             player=self.player,
                                                             state=self.state,
                                                             type=stream_type,
                                                             **local=self.local**)

In the do_plex_monitor logic from cloudplow.py

stream_count = 0
            for stream in streams:
                if stream.state == 'playing' or stream.state == 'buffering':
                    stream_count += 1
                **if stream.local == 1:
                    stream_count -= 1**

**Comment by desimaniac** [comment]
Added in https://github.com/l3uddz/cloudplow/commit/97702c82c1cafeae99f4b1c1a83b614fa2743c07
