### ISSUE TITLE
Manage service accounts better by rotating

### ISSUE THREAD

**Issue by seertenedos** [l3uddz/cloudplow#77]
If you upload a lot of data to multiple team dives using a pool of service accounts it would be great if the app remembered how much it has uploaded on each service account recently and pick the one it has uploaded the least on instead of seeming to choose the first service account and working it way though them till it finds one that works fromt he start each time.

It would also be good if in the rclone sleeps you could specify to move to the next key as well.

**Comment by seertenedos** [comment]
i have 5 jobs configured using the same server key pool and each one starts at servie key 1 and works up each time enven though other jobs and itself on past runs have gone past service key one. it really needs a memory of which one it is up to.

**Comment by garcha** [comment]
@seertenedos I'm trying to use multiple SA, and when the upload limit is hit cloudplow doesn't switch to the next SA. Anything you could point to figure out the issue?

**Comment by SaintNick1214** [comment]
This drives me crazy as well.  I even have sarotate running in background and cloudplow always decides to use 1.json when it starts and just sits there with errors not changing to another json within a reasonable amount of time.

From log:
There is 2850 available service accounts
Using service account: /opt/sa/1.json

Sounds silly just looking at it.

**Comment by saltydk** [comment]
Consdering multiple applications could be using the service accounts I don't see the point of tracking this.
