### ISSUE TITLE
Sabnzbd integration

### ISSUE THREAD

**Issue by hacktek** [l3uddz/cloudplow#78]
**Describe the problem**
I run my media through an mp4 remux workflow of my own using my own scripts. I don't exclude mkv's from upload because I don't want the remux job to create a backlog if it can't convert quickly enough but I would like to be able to control how quickly SAB downloads to give the remux job more time to finish. 

I'm currently doing this from my script but it would be cool if cloudplow could throttle SAB in a similar way to how it throttles itself when plex has active streams.

Occasionally when a lot of media is requested/downloaded at once

**Describe any solutions you think might work**

API request to SAB to limit download speed while cloudplow uploads or possibly depending on the size of the data to upload.

**Additional context**

**Comment by pushnoi** [comment]
Would like this as well. NZBGet integration is already here, would love this for SABnzbd.

**Comment by Akury83** [comment]
100% agree this would be a great feature for those of us using sabnzbd instead of nzbget
