### ISSUE TITLE
Transferred and Elapsed Time controls

### ISSUE THREAD

**Issue by shortbus** [l3uddz/cloudplow#80]
**Describe the problem**
Feature: Monitor rclone output for "Transferred" and "Elapsed time"; so that when 750 GB has been transferred (or if a specified time has elapsed) then it will move on the next sequential uploader or sync job option.

**Describe any solutions you think might work**
In the same way that the "rclone sleeps" section works you can monitor for the "Transferred:" and "Elapsed time:" 
There could be settings in the config.json that call out "transferred-limit" and "elapsed-time-limit".
Then during uploads when either "transferred-limit" and "elapsed-time-limit" the cloudplow will stop that uploader or syncer job and move onto the next job.

**Additional context**
This is to allow users to have several remotes configured and avoid hitting data caps for a team drive, for example. Yet still, be able to move on to a different team drive and upload content to the next one.

**Comment by tobifanibi** [comment]
This isn't really needed as a guide on how to create service accounts would fix this issue.
