### ISSUE TITLE
Size of upload is incorrect in Notification

### ISSUE THREAD

**Issue by Backslashh** [l3uddz/cloudplow#89]
**Describe the bug**
I have set a min-age on files that I was uploaded with Cloudplow as an rclone_extra setting. The setting seems to filter the files for upload correctly, however the notification I receive tells me it is uploading the size of the source directory, not the actual upload size.

**To Reproduce**
1. In rclone_extras, set `"--min-age": "365d"`
2. Configure dry_run so nothing is actually uploaded
3. perform a manual upload and observe the upload size in the notification (in my case, slack)
4. See the incorrect upload size.

**Expected behavior**
I would expect that the notification I receive should be for the size of the actual upload, not just the size of my source directory.

**Screenshots**
Actual size of media greater than 365d:
![image](https://user-images.githubusercontent.com/2252680/90458897-fa33a080-e142-11ea-9d4e-706822563eb9.png)

Notification from Cloudplow:
![image](https://user-images.githubusercontent.com/2252680/90458917-0a4b8000-e143-11ea-975d-c8efd0c07eeb.png)

**System Information**

 - Cloudplow Version: Master (latest)
 - Operating System: Debian Stretch

**Comment by tobifanibi** [comment]
I don't know how you would remove this behavior from the program rclone is the one handle the program handle the filtering.

The line in the code that controls that output is
path.get_size(rclone_config['upload_folder'], uploader_config['size_excludes'])

So it looks like is is the size of the folder -excluded directories

So your right once rclone adds commands that filter the size of that further down it won't be correct

**Comment by saltydk** [comment]
As stated in the previous comment this is not really something you can expect cloudplow to react to. Can always edit the command used in the path.py if you really want a fix for your particular use case.
